# -*- coding: utf-8 -*-
from odoo import api, fields, models, _


class Request(models.Model):
    _name = "cf.hospital.request"
    _inherit = ["mail.thread", 'mail.activity.mixin']
    _description = "Request"
    _rec_name = "fullname"



    id_web = fields.Integer(string='Web ID', tracking=True)
    user_id= fields.Many2one(comodel_name ='res.users',string='User ', tracking=True)
    doctor_id = fields.Many2one(comodel_name ='res.partner', string='Doctor ', tracking=True)
    nurse_id = fields.Many2one(comodel_name ='res.partner', string='Nurse ', tracking=True)
    driver_id = fields.Many2one(comodel_name ='res.partner', string='Driver ', tracking=True)
    fullname= fields.Char(string="Full Name",tracking=True,translate=True)
    # name_ar = fields.Char(string='name Arabic', required=True, tracking=True)
    # name_eng = fields.Char(string='name English', required=True, tracking=True)
    name_caregiver=fields.Char(string='CareGiver',tracking=True)
    gender = fields.Selection([('0', 'Male'), ('1', 'Female')],string='Gender' , tracking=True)
    location = fields.Char(string='Location' , tracking=True)
    governorate_id= fields.Many2one(comodel_name ='cf.hospital.governorates',string='Governorate', tracking=True)
    city_id= fields.Many2one(comodel_name ='res.country.state',string='City', tracking=True)
    adress = fields.Char(string='Adress' , tracking=True)
    adress2 = fields.Char(string='Address 2' , tracking=True)
    land_mark = fields.Char(string='Land Mark' , tracking=True)
    floor = fields.Char(string='Floor' , tracking=True)
    apartment = fields.Char(string='Apartment' , tracking=True)
    phone = fields.Char(string='Phone' , tracking=True)
    phone2 = fields.Char(string='Phone 2' , tracking=True)
    whatapp = fields.Integer(string='Whats app',tracking=True)
    whatapp2 = fields.Integer(string='Whats app2',tracking=True)
    whatsApp_group = fields.Char(string='Whats app Group',tracking=True)
    age = fields.Char(string='Age',tracking=True)
    type = fields.Selection([('0', 'ONE'), ('1', 'TWO'),('2','THREE')],string='Type',tracking=True)
    covid19 = fields.Boolean(string='Covid 19 Test')
    corporate_id = fields.Many2one(comodel_name ='cf.hospital.company',string='Corporate',tracking=True)
    specialty_id  = fields.Many2one(comodel_name ='cf.hospital.specialties',string='Speciality',tracking=True)
    service_id = fields.Many2one(comodel_name ='cf.hospital.service',string='Services',tracking=True)
    package_id = fields.Many2one(comodel_name ='cf.hospital.packages',string='Package',tracking=True)
    physician =  fields.Many2one(comodel_name ='cf.hospital.physician',string='Physician',tracking=True)
    visit_time_day =fields.Date(string='Visit Day',tracking=True)
    visit_time_from  = fields.Datetime(string='Visit time form',tracking=True)
    visit_time_to = fields.Datetime(string='Visit time to',tracking=True)
    expectation_cost = fields.Float(string='Expectation cost', digits=(8, 2), required=True, tracking=True)
    real_cost = fields.Float(string='Real cost', digits=(8, 2), required=True, tracking=True)
    medical_type_id = fields.Many2one(comodel_name ='cf.hospital.medicaltype',string='Medical Type',tracking=True)
    price_list_id = fields.Many2one(comodel_name ='cf.hospital.pricelist',string='Price List',tracking=True)
    bill_serial =  fields.Char(string='Bill Serial',tracking=True)
    pay_or_not = fields.Boolean(string='Payment',tracking=True)
    code_zone_patient_id = fields.Char(string='Code Zone ID',tracking=True)
    bed_number = fields.Char(string='Bed Number',tracking=True)
    symptoms = fields.Char(string='Symptoms',tracking=True)
    doc_note = fields.Char(string='Doc Note',tracking=True)
    come_from = fields.Char(string='Come From',tracking=True)
    reason_out =  fields.Char(string='Reason Out',tracking=True)
    Long =  fields.Char(string='Long',tracking=True)
    date_out = fields.Date(string='Date Out',tracking=True)
    date_in =  fields.Date(string='Date In',tracking=True)
    diagnose = fields.Char(string='Diagnose',tracking=True)
    history = fields.Char(string='History',tracking=True)
    co = fields.Char(string='co',tracking=True)
    end_service_date = fields.Date(string='End Service Date',tracking=True)
    schedule_date = fields.Date(string='Schedule Date',tracking=True)
    nurse_evaluation = fields.Char(string='Nurse Evaluation',tracking=True)
    satisfaction = fields.Char(string='Satisfaction',tracking=True)
    nomination_rate = fields.Char(string='Nomination Rate',tracking=True)
    speed_services_overall = fields.Char(string='Speed Service Overall',tracking=True)
    reason_cancel = fields.Char(string='Cancelation Reason',tracking=True)
    feedback = fields.Char(string='Feedback',tracking=True)
    doc_rate = fields.Integer(string='doc_rate',tracking=True)
    user_rate = fields.Integer(string='User Rate',tracking=True)
    opd_admin_id = fields.Many2one(comodel_name ='res.users',string='Admin 1',tracking=True)
    opd2_admin_id = fields.Many2one(comodel_name ='res.users',string='Admin 2',tracking=True)
    cc_admin_id = fields.Many2one(comodel_name ='res.users',string='CC Admin',tracking=True)
    admin_id_in_out = fields.Many2one(comodel_name ='res.users',string='Admin ID in out',tracking=True)
    status_doc = fields.Boolean(string='Status Doc',tracking=True)
    status_user = fields.Boolean(string='Status Usre',tracking=True)
    status_cc = fields.Boolean(string='Status CC',tracking=True)
    status_in_out = fields.Boolean(string='Status IN OUT',tracking=True)
    created_by = fields.Char(string='created by',tracking=True)
    web_created_at = fields.Datetime(string='created_at', tracking=True)
